name: Suzology
favicon: null
layout_spectrum: 0.7497419242281467
typography_spectrum: 0.11833159672096372
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.2091983612626791
  lightness: 0.7080162344500422
  saturation: 0.4850878482684493
  rhythmicContrast: 0.00768081471323967
purpose: []
